/** 22 张大阿卡纳：每张牌独立的正/逆位意象与分支语义 */

export const MAJOR_PROFILES = {
  major_00: {
    image: '悬崖边的旅人、白狗与轻装的行囊',
    upright: {
      core: '零起点的信任与一次真心的出发',
      omen: '偶然的好消息、路人的善意、计划外的邀请',
      possibility: '全新赛道、跨界尝试、说走就走的小冒险',
      opportunity: '先迈出最小一步，宇宙会在路上补全资源',
      warning: '不是无视风险，而是别把「未知」全当成灾难预演',
      shadow: '旁人觉得你天真，你其实在做自己的版本的选择',
    },
    reversed: {
      core: '莽撞与停滞并存：要么冲太快，要么迟迟不出发',
      omen: '迟到、忘事、承诺放空、行程临时打乱',
      possibility: '旧包袱没放下，新门就开不了',
      opportunity: '从一次草率里学会做功课，仍是成长',
      warning: '用「再等等」掩盖恐惧，时间会悄悄带走选项',
      shadow: '逃避责任时，仍会用「自由」当借口',
    },
  },
  major_01: {
    image: '桌前四元素齐备的魔术师',
    upright: {
      core: '意志聚焦，把零散资源捏成可见成果',
      omen: '灵感落地、谈判顺利、技能被看见',
      possibility: '主动创造局面，而非等待被点名',
      opportunity: '此刻适合开场、提案、公开表达、动手做样机',
      warning: '别同时开太多线，分散会削弱魔力',
      shadow: '自信若过头，容易显得操控或浮夸',
    },
    reversed: {
      core: '才华闲置、话术大于行动、工具摆错地方',
      omen: '项目搁浅、设备故障、沟通误会',
      possibility: '重新排列优先级，仍能找回主导权',
      opportunity: '诚实承认「哪一步没做」，比表演专业更重要',
      warning: '自欺或夸大承诺，会反噬信誉',
      shadow: '把失败全怪外界，忽略自己没专注',
    },
  },
  major_02: {
    image: '月冠与帷幕后的女祭司',
    upright: {
      core: '静默中的洞察，答案在感受而非喧哗里',
      omen: '梦兆、重复符号、直觉突然清晰',
      possibility: '深层学习、灵性觉醒、看见被忽略的真相',
      opportunity: '少说话多观察；记录梦境与第一感',
      warning: '过度封闭会被误解为冷漠',
      shadow: '秘密若必要，请选择值得守密的人',
    },
    reversed: {
      core: '压抑直觉、情绪淤积、秘密反噬',
      omen: '流言、误解、情绪爆发、隐私泄露',
      possibility: '说出一句真话，迷雾会退一层',
      opportunity: 'therapy式对话、写日记、与信任的人深谈',
      warning: '别用神秘包装逃避面对现实',
      shadow: '冷暴力或被动攻击，伤人也伤己',
    },
  },
  major_03: {
    image: '丰饶田野上的皇后',
    upright: {
      core: '滋养、创造、以感官与耐心孕育成果',
      omen: '怀孕隐喻、项目发芽、家居变舒适',
      possibility: '艺术、料理、园艺、亲密关系升温',
      opportunity: '对自己好一点，丰盛会向外扩散',
      warning: '过度照顾他人而掏空自己',
      shadow: '占有欲以「爱」之名出现时要辨认',
    },
    reversed: {
      core: '创造力枯竭、依赖、滋养变控制',
      omen: '身体不适、财务吃紧、关系里付出失衡',
      possibility: '重建边界后，魅力会回来',
      opportunity: '把照顾先转向自己的身体与房间',
      warning: '情绪性消费或暴饮暴食作代偿',
      shadow: '用牺牲绑架对方，并非真正的爱',
    },
  },
  major_04: {
    image: '石座上的皇帝',
    upright: {
      core: '结构、责任、为长远目标立法',
      omen: '升职、签约、父亲式贵人、规则变清晰',
      possibility: '搭团队、定制度、买房置产',
      opportunity: '做决策者该做的艰难但公正的选择',
      warning: '僵化会扼杀灵活，留一条例外通道',
      shadow: '权威若缺温度，亲近的人会疏远',
    },
    reversed: {
      core: '失控、暴烈、或逃避承担',
      omen: '权力斗争、合约纠纷、硬碰受伤',
      possibility: '软化的领导方式反而更能服众',
      opportunity: '承认脆弱，不等于放弃主导',
      warning: '专制或赌气决策，代价由集体买单',
      shadow: '外强中干时，最爱用脾气掩盖不安',
    },
  },
  major_05: {
    image: '祝福手势的教皇与信徒',
    upright: {
      core: '传统、仪式、在信念体系里找坐标',
      omen: '师长引荐、考试通过、婚礼订婚',
      possibility: '加入社群、拜师、系统学习',
      opportunity: '向有经验者请教，可少走冤枉路',
      warning: '盲从权威前，先问「这规则仍适合我吗」',
      shadow: '道德高地若用来评判他人，会变成牢笼',
    },
    reversed: {
      core: '质疑教条、信仰动摇、局外人视角',
      omen: '与长辈冲突、退学离职、价值观撕裂',
      possibility: '走出适合自己的灵性/职业路径',
      opportunity: '打破不适配的形式，保留核心价值',
      warning: '为反对而反对，也会迷失',
      shadow: '叛逆里若缺建设，只剩破坏',
    },
  },
  major_06: {
    image: '天使见证下的恋人',
    upright: {
      core: '价值对齐、选择、关系里的真实自我',
      omen: '心动、复合信号、重要合同缔结',
      possibility: '双选合一、合伙、公开关系',
      opportunity: '诚实说出偏好，对齐比讨好长久',
      warning: '别在两人之间反复横跳消耗信任',
      shadow: '浪漫滤镜下，仍要看现实条件',
    },
    reversed: {
      core: '失衡、三角、逃避选择',
      omen: '争吵、冷战、承诺反悔',
      possibility: '分离后的自我重建，反而更清醒',
      opportunity: '先独自厘清价值观，再谈合并',
      warning: '用暧昧逃避责任，会拖成长痛',
      shadow: '把依赖误当成爱',
    },
  },
  major_07: {
    image: '战车与黑白狮身人面',
    upright: {
      core: '意志统一、冲破分歧、向目标疾驰',
      omen: '竞赛胜出、搬家远行、矛盾暂时压制',
      possibility: '短期冲刺成功、品牌曝光',
      opportunity: '把内耗双方拉到同一战线',
      warning: '胜利后别忘休整，战车也会磨损',
      shadow: '过度控制伴侣/同事，引发反弹',
    },
    reversed: {
      core: '方向涣散、失控、蛮力失效',
      omen: '车祸隐喻、项目脱轨、团队分裂',
      possibility: '慢下来重新校准目标，仍能上路',
      opportunity: '承认「并非所有仗都值得打」',
      warning: '赌气硬冲，可能两败俱伤',
      shadow: '外表强势，内心其实没有地图',
    },
  },
  major_08: {
    image: '轻抚狮口的女子',
    upright: {
      core: '以柔克刚、驯服本能、耐心与自信',
      omen: '冲突缓和、身体康复、宠物/孩子带来慰藉',
      possibility: '长期关系修复、习惯养成',
      opportunity: '用稳定重复代替爆发式努力',
      warning: '压抑情绪太久，仍需安全出口',
      shadow: '温柔不是没底线',
    },
    reversed: {
      core: '自我怀疑、软弱、或以强硬掩盖恐惧',
      omen: '信心崩塌、羞怯、攻击性失控',
      possibility: '从小胜利重拾自我效能感',
      opportunity: '寻求支持，不等于懦弱',
      warning: '别在关系里测试对方底线',
      shadow: '讨好与爆发两个极端轮换',
    },
  },
  major_09: {
    image: '提灯的隐者',
    upright: {
      core: '独处、反省、慢光照明',
      omen: '贵人寡言、深夜顿悟、退隐养生',
      possibility: '学术、修行、写作、深度研究',
      opportunity: '暂时退出喧嚣，答案会浮上来',
      warning: '孤立若过久，会错过必要合作',
      shadow: '用清高躲避亲密',
    },
    reversed: {
      core: '封闭、拒绝指引、或迷失在孤独',
      omen: '孤僻、迷路、老人健康问题',
      possibility: '打开门缝，让信任的人进来',
      opportunity: '把洞察写成可分享的语言',
      warning: '别用「没人懂我」固化停滞',
      shadow: '冷漠是受伤后的盔甲',
    },
  },
  major_10: {
    image: '转动的命运之轮',
    upright: {
      core: '周期转折、机缘起落、顺势而为',
      omen: '意外转机、中奖隐喻、旧友回归',
      possibility: '局面翻盘、行业风口',
      opportunity: '在上升弧段多存资源、多结善缘',
      warning: '高峰时别傲慢，低谷时别绝望',
      shadow: '把偶然当能力，会摔更狠',
    },
    reversed: {
      core: '厄运感、抗拒变化、重复踩坑',
      omen: '卡顿、循环失败、外部环境不利',
      possibility: '承认周期，就能主动调整策略',
      opportunity: '小步试错，等待轮盘回正',
      warning: '受害者叙事会剥夺主动权',
      shadow: '赌性上瘾，指望一夜翻身',
    },
  },
  major_11: {
    image: '持剑与天秤的正义',
    upright: {
      core: '公平、因果、清晰抉择',
      omen: '法律有利、真相大白、合同公正',
      possibility: '仲裁成功、道德平反',
      opportunity: '用证据说话，少情绪勒索',
      warning: '冷酷判决也会伤人',
      shadow: '正义若缺慈悲，只剩冰冷',
    },
    reversed: {
      core: '不公、逃避责任、偏见',
      omen: '纠纷拖延、证据不足、自责或责人过度',
      possibility: '先处理内心愧疚，外在才平衡',
      opportunity: '主动补偿、道歉、重建信任',
      warning: '别在模糊地带占小便宜',
      shadow: '双重标准会被反噬',
    },
  },
  major_12: {
    image: '倒吊人悬挂的宁静',
    upright: {
      core: '自愿暂停、换位思考、顿悟',
      omen: '等待期、被动休息、视角翻转',
      possibility: '牺牲短期利益换长期洞见',
      opportunity: '停止挣扎，看见此前看不见的路',
      warning: '别变成永久拖延的借口',
      shadow: '自我感动式牺牲，对方未必需要',
    },
    reversed: {
      core: '无谓牺牲、拖延、抗拒暂停',
      omen: '僵持、无效等待、身体僵硬',
      possibility: '落地行动比空想更有用',
      opportunity: '结束「表演式受苦」',
      warning: '硬撑会伤关节与神经',
      shadow: '把停滞美化成修行',
    },
  },
  major_13: {
    image: '白马与死神旗',
    upright: {
      core: '结束、蜕变、旧章落幕',
      omen: '分手、离职、剪发、大扫除',
      possibility: '重生前的必要清空',
      opportunity: '亲手关门，比被拖走体面',
      warning: '哀悼需要仪式与时间',
      shadow: '对改变的恐惧，常伪装成留恋',
    },
    reversed: {
      core: '抗拒结束、僵尸关系/项目',
      omen: '拖泥带水、旧疾复发、无法前进',
      possibility: '真正告别后，能量立刻回流',
      opportunity: '写下「我已不再需要…」清单',
      warning: '半死不活最耗人',
      shadow: '害怕未知，宁愿烂在熟悉里',
    },
  },
  major_14: {
    image: '双杯调和的节制',
    upright: {
      core: '调和、耐心、适度节奏',
      omen: '康复、和解、配方找到',
      possibility: '跨界融合、长期疗愈见效',
      opportunity: '每天一点点，胜过爆发三天',
      warning: '中庸不是回避冲突',
      shadow: '过度妥协会失去自我',
    },
    reversed: {
      core: '失衡、急躁、极端',
      omen: '成瘾、暴饮暴食、关系忽冷忽热',
      possibility: '建立新节律，身体先回应',
      opportunity: '减少一种过量，增加一种滋养',
      warning: '别用放纵庆祝，用放纵逃避',
      shadow: '全有或全无的思维',
    },
  },
  major_15: {
    image: '锁链松垮的恶魔',
    upright: {
      core: '欲望、依附、看得见的束缚',
      omen: '诱惑、金钱挂钩、性吸引力',
      possibility: '承认阴影，反而获得自由',
      opportunity: '问「谁在获益于我的不改变」',
      warning: '成瘾模式会温柔地变紧',
      shadow: '你比想象中更有选择权',
    },
    reversed: {
      core: '挣脱、觉察、打破枷锁',
      omen: '戒断反应、离开有毒关系',
      possibility: '真相刺眼，但是解放',
      opportunity: '寻求专业帮助或社群支持',
      warning: '别用另一种瘾替换旧瘾',
      shadow: '内疚感可能拖住脚步',
    },
  },
  major_16: {
    image: '高塔雷击',
    upright: {
      core: '突变、假象崩塌、震撼中的真相',
      omen: '突发消息、架构瓦解、震惊',
      possibility: '废墟上建更诚实的生活',
      opportunity: '先安全落地，再重建',
      warning: '别在余震期做永久决定',
      shadow: '早该倒的墙，宇宙帮你推',
    },
    reversed: {
      core: '延迟爆炸、否认、小裂痕被忽视',
      omen: '慢性危机、焦虑预感、结构吱呀',
      possibility: '主动小拆改，避免大崩塌',
      opportunity: '提前沟通、提前止损',
      warning: '压抑真相，塔仍会倒',
      shadow: '恐惧灾难想象，反而制造内耗',
    },
  },
  major_17: {
    image: '星空下的裸女与水瓶',
    upright: {
      core: '希望、疗愈、信念回归',
      omen: '灵感回流、皮肤变好、远方好消息',
      possibility: '长期项目见光、公益被认可',
      opportunity: '温柔坚持，黑夜不是终点',
      warning: '别只靠愿景，忽略脚下',
      shadow: '理想主义需要日程表',
    },
    reversed: {
      core: '失望、信心裂缝、疗愈中断',
      omen: '创意阻塞、乐观落空',
      possibility: '小确幸仍在，只是被遮住',
      opportunity: '缩小目标，重建可完成的循环',
      warning: '别用 cynicism 保护受伤的心',
      shadow: '把「没希望」当身份认同',
    },
  },
  major_18: {
    image: '双犬与月亮之路',
    upright: {
      core: '潜意识、迷雾、梦与恐惧',
      omen: '梦境强烈、直觉过敏、误会',
      possibility: '艺术、心理、神秘学通道打开',
      opportunity: '记录梦、区分想象与事实',
      warning: '猜疑未证实前，别下定论',
      shadow: '恐惧放大时，现实仍可能安全',
    },
    reversed: {
      core: '迷雾散去、恐惧命名、真相渐清',
      omen: '秘密曝光、焦虑缓解',
      possibility: '走出自我欺骗',
      opportunity: '把害怕的事写下来，强度会下降',
      warning: '别刚清晰就又逃回幻觉',
      shadow: '依赖药物/幻想逃避',
    },
  },
  major_19: {
    image: '孩童与白马的太阳',
    upright: {
      core: '喜悦、成功、活力外显',
      omen: '庆祝、升职、怀孕、旅行晴朗',
      possibility: '被看见、被喜爱、项目开花',
      opportunity: '大方展示成果，别谦虚到隐藏',
      warning: '烈日也会晒伤，记得休息',
      shadow: '快乐若表演，内心仍空虚',
    },
    reversed: {
      core: '乐观延迟、热情受挫、阴霾',
      omen: '派对取消、信心低落',
      possibility: '乌云是暂时的，光源仍在',
      opportunity: '从身体找快乐：运动、晒太阳',
      warning: '别用假笑维持形象',
      shadow: '童年未愈的快乐需求',
    },
  },
  major_20: {
    image: '天使号角与复活人群',
    upright: {
      core: '觉醒、召唤、回顾与赦免',
      omen: '故人联系、旧案重启、灵魂震动',
      possibility: '第二人生、改行、公开真相',
      opportunity: '回应内心「我早就知道该…」',
      warning: '召唤来了，仍要一步步走',
      shadow: '别用宏大使命逃避日常责任',
    },
    reversed: {
      core: '自我否定、逃避召唤、无法原谅',
      omen: '后悔、失眠、旧错纠缠',
      possibility: '对自己仁慈，才能听见号角',
      opportunity: '写一封不寄出的信完成仪式',
      warning: '拖延觉醒，痛会重复播放',
      shadow: '用忙碌盖住未了之事',
    },
  },
  major_21: {
    image: '花环中舞蹈的世界',
    upright: {
      core: '完成、整合、圆满与新的起点',
      omen: '毕业、移民成功、婚礼、大项目收官',
      possibility: '全球视野、跨界整合、名声',
      opportunity: '庆祝后，规划下一周期',
      warning: '圆满里别停滞，宇宙要你再进化',
      shadow: '完美主义拖延最后一步',
    },
    reversed: {
      core: '未完成、差一口气、迟迟不能收尾',
      omen: '签证延迟、尾款不到、毕业延期',
      possibility: '补齐一小块，门就关得上',
      opportunity: '列出「还差什么」清单逐项清',
      warning: '别在99%处放弃',
      shadow: '害怕结束后面对空白',
    },
  },
};
